language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.1.1
    - android-26
before_install:
  - yes | sdkmanager "platforms;android-26"
before_script:
  - chmod +x gradlew
script:
   - ./gradlew build connectedCheck
