sudo: false
language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.3

    # The SDK version used to compile your project
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

before_install:
  - pwd
  - ls -la
  - chmod +x /.gradlew
script:
  - /.gradlew clean build"
