sudo: required
language: android
jdk: oraclejdk8
android:

 components:
    - platform-tools
    - tools
    - build-tools-26.1.1
    - android-26
    - extra-android-m2repository
 before_install:
    - chmod +x gradlew
##before_script:
 #- chmod +x gradlew
 
script:
- ./gradlew build --stacktrace
- chmod +x ./gradlew build connectedCheck
